spring:
  application:
    name: user-service

  flyway:
    default-schema: user_db
#    enabled: false
#    baseline-on-migration: true
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

server:
  port: 8003

