spring:
  application:
    name: user-service

  flyway:
    default-schema: user_db
#    enabled: false
#    baseline-on-migration: true
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

server:
  port: 8001

invoice:
  service:
    url: http://localhost:8002

feign:
  client:
    config:
      invoice-service-feign-client:
        connectTimeout: 5000
        readTimeout: 8000

